apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kubescrub-web
  name: kubescrub-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubescrub-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubescrub-web
    spec:
      containers:
      - image: cmwylie19/kubescrub-ui:0.0.1
        name: kubescrub-ui
        ports:
        - containerPort: 8080
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kubescrub-web
  name: kubescrub-web
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubescrub-web
status:
  loadBalancer: {}
