apiVersion: v1
data:
  name: robot
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cm
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rand
  name: rand
spec:
  containers:
  - image: nginx
    name: nginx
    env: 
    - name: cm 
      valueFrom:
        configMapKeyRef:
          name: cm
          key: name
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kubescrub
  name: kubescrub
spec:
  containers:
  - image: cmwylie19/kubescrub:0.0.1
    name: kubescrub
    command: ["./kubescrub", "serve" ,"-p", "8080"]
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: kubescrub
  name: kubescrub
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: kubescrub